# -*- coding: utf-8 -*-
"""Emotion_news_set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1foTd8v0EnYKruJSvWOFDrbWwfOmUrGqs
"""

!pip install transformers torch pandas newsapi-python

import pandas as pd
from newsapi import NewsApiClient
from transformers import pipeline

# --- CONFIGURATION ---
NEWS_API_KEY = "7e643fe1771e4cebba806bb303eafec3" # <--- Put your key inside the quotes

print("1. Loading the j-hartmann AI Model (This takes a moment)...")
# device=0 forces the model to use the fast Colab GPU
emotion_classifier = pipeline(
    "text-classification",
    model="j-hartmann/emotion-english-distilroberta-base",
    device=0
)

print("2. Connecting to NewsAPI...")
newsapi = NewsApiClient(api_key=NEWS_API_KEY)

# Fetching a massive variety of news using broad categories
articles_response = newsapi.get_everything(
    q='world OR politics OR business OR technology OR science OR health OR sports OR entertainment',
    language='en',
    page_size=100
)
articles_data = articles_response['articles']

print(f"Fetched {len(articles_data)} articles. Starting emotion analysis...")

processed_news = []

for article in articles_data:
    # Skip articles that are broken or missing descriptions
    if not article.get('title') or not article.get('description'):
        continue

    try:
        # The AI reads the description and outputs the emotion
        text_to_analyze = article['description']
        result = emotion_classifier(text_to_analyze)[0]

        # Structure this EXACTLY like your MySQL diagram
        news_row = {
            "title": article['title'],
            "description": article['description'],
            "url": article['url'],
            "source_name": article['source']['name'],
            "published_at": article['publishedAt'],
            "emotion_label": result['label'],
            "emotion_score": round(result['score'], 4)
        }
        processed_news.append(news_row)

    except Exception as e:
        continue

print("3. Saving the data...")
df = pd.DataFrame(processed_news)
df.to_csv("news_emotion_data.csv", index=False)
print("✅ Done! Your data is formatted and saved as 'news_emotion_data.csv'")

import pandas as pd

# Read the CSV file you just created
df = pd.read_csv("news_emotion_data.csv")

# Display the first 20 articles as a clean table
display(df.head(20))

# Print the total number of articles you successfully grabbed
print(f"\nTotal articles ready for your database: {len(df)}")

from google.colab import files

files.download('/content/news_emotion_data.csv')